project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - donnees.qmd
    - code/chap1.qmd
    - code/chap2.qmd
    - code/chap3.qmd
    - code/chap4.qmd
    - code/chap5.qmd
    - code/chap6.qmd
    - code/chap7.qmd
    - code/chap8.qmd
    - code/chap9.qmd
    - code/chap10.qmd
    - code/chap11.qmd
    - code/chap12.qmd
    - code/chap13.qmd
    - code/chap14.qmd
    - code/chap15.qmd
    - code/chap16.qmd
    - code/chap17.qmd
    - correction/chap1.qmd
    - correction/chap2.qmd
    - correction/chap3.qmd
    - correction/chap4.qmd
    - correction/chap5.qmd
    - correction/chap6.qmd
    - correction/chap7.qmd
    - correction/chap8.qmd
    - correction/chap9.qmd
    - correction/chap11.qmd
    - correction/chap12.qmd
    - correction/chap13.qmd
    - correction/chap17.qmd

website:
  title: "Régression avec R"
#  navbar:
#    background: primary
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd
  reader-mode: true
#  site-path: "/page_perso/" #important pour la page 404.html
  page-navigation: true
  sidebar: 
    style: "floating"
    search: true
    #background: "#D9E3E4" #rgb(118, 215, 196)
    collapse-level: 1
#    foreground: red
    contents:
      - index.qmd
      - donnees.qmd
      - section: "Codes R"
        contents:
          - section: I Introduction au modèle linéaire
            contents:
              - code/chap1.qmd
              - code/chap2.qmd
              - code/chap3.qmd
          - section: II Inférence
            contents:
              - code/chap5.qmd
              - code/chap6.qmd
          - section: III Réduction de dimension
            contents:
              - code/chap7.qmd
              - code/chap8.qmd
              - code/chap9.qmd
              - code/chap10.qmd
          - section: IV Le modèle linéairé généralisé
            contents:
              - code/chap11.qmd
              - code/chap12.qmd
              - code/chap13.qmd
              #- code/chap14.qmd
              - code/chap15.qmd
          - section: V Introduction à la régression non paramétrique
            contents:
              - code/chap16.qmd
              - code/chap17.qmd
      - section: "Correction des exercices"
        contents:
          - section: I Introduction au modèle linéaire
            contents:
              - correction/chap1.qmd
              - correction/chap2.qmd
              - correction/chap3.qmd
              - correction/chap4.qmd
          - section: II Inférence
            contents:
              - correction/chap5.qmd
              - correction/chap6.qmd
          - section: III Réduction de dimension
            contents:
              - correction/chap7.qmd
              - correction/chap8.qmd
              - correction/chap9.qmd
          - section: IV Le modèle linéairé généralisé
            contents:
              - correction/chap11.qmd
              - correction/chap12.qmd
              - correction/chap13.qmd
          - section: V Introduction à la régression non paramétrique
            contents:
              - correction/chap17.qmd

lang: fr

format:
  html:
    backgroundcolor: "#D9E3E4" #White #LightYellow
    #include-before-body:
    #  - file: _preamble.html
    crossref: 
      exr-prefix: exercice
      eq-prefix: équation
    theme: 
      - united
#      - darkly
#      - custom.scss
    css: styles.css
    page-layout: full
    linkcolor: red
    link-external-newwindow: true
    fontsize: 12pt
    cite-method: citeproc
    biblio-style: apalike
    biblio-title: "Arti"
#    page-layout: full
#    max-width: 18em
execute:
  warning: false
  echo: true
#  cache: false
  freeze: auto

editor: source
